P=int(input("enter the value of P:"))
q=int(input("enter the value of q:"))
r=int(input("enter the value of r:"))
z=int(input("enter the value of z:"))
print("result of P>q>r is :",P>q>r)
print("result of P<q<r is :",P<q<r)
print("result of P<q and q<z is :",P<q and q<z)
print("result of P<q or q<z is :",P<q or q<z)
